#ifndef _VIRREG_HAL_H
#define _VIRREG_HAL_H

typedef struct{
	unsigned char hw_version;
	unsigned char fw_version;
	unsigned char sw_version;
}sys_version_s;

unsigned int virtualreg_init_reg(void);
void virreg_get_info_model(unsigned int *model);
void virreg_set_info_model(unsigned int model);
void virreg_get_info_version(sys_version_s * version);
void virreg_get_sys_reset(unsigned int *reset);
void virreg_set_sys_reset(unsigned int reset);
void virreg_get_sys_start(unsigned int *start);
void virreg_set_sys_start(unsigned int start);
void virreg_get_global_int_ctrl(unsigned int *ctrl);
void virreg_set_global_int_ctrl(unsigned int ctrl);
void virreg_get_trans_int_ctrl(unsigned int *ctrl);
void virreg_set_trans_int_ctrl(unsigned int ctrl);
void virreg_get_wave_int_ctrl(unsigned int *ctrl);
void virreg_set_wave_int_ctrl(unsigned int ctrl);
void virreg_get_stay_int_ctrl(unsigned int *ctrl);
void virreg_set_stay_int_ctrl(unsigned int ctrl);
void virreg_get_global_int_status(unsigned int *status);
void virreg_set_global_int_status(unsigned int status);
void virreg_get_trans_int_status(unsigned int *status);
void virreg_set_trans_int_status(unsigned int status);
void virreg_get_wave_int_status(unsigned int *status);
void virreg_set_wave_int_status(unsigned int status);
void virreg_get_stay_int_status(unsigned int *status);
void virreg_set_stay_int_status(unsigned int status);
void virreg_get_pos_lc_xy(unsigned int *x, unsigned int *y);
void virreg_set_pos_lc_xy(unsigned int x, unsigned int y);
void virreg_get_pos_lc_z(unsigned int *z);
void virreg_set_pos_lc_z(unsigned int z);
void virreg_get_pos_l1_xy(unsigned int *x, unsigned int *y);
void virreg_set_pos_l1_xy(unsigned int x, unsigned int y);
void virreg_get_pos_l1_z(unsigned int *z);
void virreg_set_pos_l1_z(unsigned int z);
void virreg_get_pos_l2_xy(unsigned int *x, unsigned int *y);
void virreg_set_pos_l2_xy(unsigned int x, unsigned int y);
void virreg_get_pos_l2_z(unsigned int *z);
void virreg_set_pos_l2_z(unsigned int z);
void virreg_get_pos_l3_xy(unsigned int *x, unsigned int *y);
void virreg_set_pos_l3_xy(unsigned int x, unsigned int y);
void virreg_get_pos_l3_z(unsigned int *z);
void virreg_set_pos_l3_z(unsigned int z);
void virreg_get_pos_l4_xy(unsigned int *x, unsigned int *y);
void virreg_set_pos_l4_xy(unsigned int x, unsigned int y);
void virreg_get_pos_l4_z(unsigned int *z);
void virreg_set_pos_l4_z(unsigned int z);
void virreg_get_pos_l5_xy(unsigned int *x, unsigned int *y);
void virreg_set_pos_l5_xy(unsigned int x, unsigned int y);
void virreg_get_pos_l5_z(unsigned int *z);
void virreg_set_pos_l5_z(unsigned int z);
void virreg_get_pos_rc_xy(unsigned int *x, unsigned int *y);
void virreg_set_pos_rc_xy(unsigned int x, unsigned int y);
void virreg_get_pos_rc_z(unsigned int *z);
void virreg_set_pos_rc_z(unsigned int z);
void virreg_get_pos_r1_xy(unsigned int *x, unsigned int *y);
void virreg_set_pos_r1_xy(unsigned int x, unsigned int y);
void virreg_get_pos_r1_z(unsigned int *z);
void virreg_set_pos_r1_z(unsigned int z);
void virreg_get_pos_r2_xy(unsigned int *x, unsigned int *y);
void virreg_set_pos_r2_xy(unsigned int x, unsigned int y);
void virreg_get_pos_r2_z(unsigned int *z);
void virreg_set_pos_r2_z(unsigned int z);
void virreg_get_pos_r3_xy(unsigned int *x, unsigned int *y);
void virreg_set_pos_r3_xy(unsigned int x, unsigned int y);
void virreg_get_pos_r3_z(unsigned int *z);
void virreg_set_pos_r3_z(unsigned int z);
void virreg_get_pos_r4_xy(unsigned int *x, unsigned int *y);
void virreg_set_pos_r4_xy(unsigned int x, unsigned int y);
void virreg_get_pos_r4_z(unsigned int *z);
void virreg_set_pos_r4_z(unsigned int z);
void virreg_get_pos_r5_xy(unsigned int *x, unsigned int *y);
void virreg_set_pos_r5_xy(unsigned int x, unsigned int y);
void virreg_get_pos_r5_z(unsigned int *z);
void virreg_set_pos_r5_z(unsigned int z);
void virreg_get_static_gest(unsigned int *gest);
void virreg_set_static_gest(unsigned int gest);
void virreg_get_wave_gest(unsigned int *gest);
void virreg_set_wave_gest(unsigned int gest);
void virreg_get_stay_gest(unsigned int *gest);
void virreg_set_stay_gest(unsigned int gest);
void virreg_get_trans_from(unsigned int *gest);
void virreg_set_trans_from(unsigned int gest);
void virreg_get_trans_to(unsigned int *gest);
void virreg_set_trans_to(unsigned int gest);

#endif /* _VIRREG_HAL_H */
